### ISSUE TITLE
Week 06 Day 2 - A Sound Board with Sass

### ISSUE THREAD

**Issue by ambethia** [benjaminkent/assignments#21]
In this assignment, you'll start with a partially complete Sound Board application and make it your own.

## Objectives

- Use features of Sass to style an application
- Practice React

## Requirements

Starting from the [implementation we created in class](https://github.com/suncoast-devs/cohort-xi/tree/master/week-06/day-2/sound-board), create your own Sound Board application.

Note the addition of `node-sass` to the project's dependencies.

### Explorer Mode

- [ ] Have at least 3 sound boards defined in `library.js`, with at least 4 sounds each.
- [ ] Use Sass for your CSS, explore and use the following features:
  - [ ] Variable
  - [ ] Nesting
  - [ ] [Functions](https://sass-lang.com/documentation/Sass/Script/Functions.html)

### Adventure Mode

- [ ] Use these Sass features
  - [ ] Mixins
  - [ ] Inheritance
  - [ ] Break your styles into multiple files using `@import`

### Epic Mode

- [ ] Create a "Video Clip" board, that plays different video clips when thumbnails are clicked.

## Additional Resources

- https://sass-lang.com/guide

**Comment by benjaminkent** [comment]
http://soundboard-benjaminjehl.surge.sh/cage, https://github.com/benjaminkent/soundboard

**Comment by ambethia** [comment]
Your homework was marked: **Meets Expectations**

![Yas](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBDQT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--eb161dfb00865249fe33bc4a730793f1eef22b19/neil.gif)
> &ldquo;Yas&rdquo;
__&mdash; via **[Jason L Perry](https://gifs.suncoast.io/venerations/3)**__
