### ISSUE TITLE
Week 07 Day 2 - Intro to Phaser Games

### ISSUE THREAD

**Issue by gstark** [benjaminkent/assignments#24]
## Using a Front End Gaming Library

In this assignment, you'll build a simple game

## Objectives

- Learn a new front end library
- Experiment with writing games

### Explorer Mode

- [ ] Get the demo we did in class working locally.
- [ ] Play with changing the physics settings in the game to adjust the game play.
- [ ] Update the images to your own style.
- [ ] Add a new feature to, or change an existing feature of, the game

### Adventure Mode

- [ ] Modify your game to a new game, or create your own!

**Comment by benjaminkent** [comment]
played with and changed some settings. changed styles - https://github.com/benjaminkent/first-phaser-game, http://first-phaser-game-benjaminjehl.surge.sh/

**Comment by gstark** [comment]
Fun!

**Comment by gstark** [comment]
Your homework was marked: **Meets Expectations**

![Great job!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBJdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--8167037ff2098b5e812290b56d35e1113c17439d/giphy-downsized.gif)
> &ldquo;Great job!&rdquo;
__&mdash; via **[Jason L Perry](https://gifs.suncoast.io/venerations/24)**__
