### ISSUE TITLE
Week 01 Day 3 - Flexbox

### ISSUE THREAD

**Issue by gstark** [benjaminkent/assignments#3]
Now that we have learned the power of flexbox we will apply it to the sites we are building. We'll also go back to a past assignment and see how flexbox would simplify our HTML and CSS.

## Objectives

- Build on your knowledge of HTML & CSS
- Use flexbox techniques layout pages.
- Implement, from scratch, a given design
- Understand HTML/CSS Layout
- Be able to place elements on a page where you want them.

## Requirements

- You should strive to implement the design as close as possible, though, especially if you've never touch HTML or CSS before, this can be extraordinarily difficult, and will take a lot of practice and mileage.

- **Note**: You should complete at least the tasks given for _explorer_ mode as listed below before turning in the assignment, as well as before attempting _adventure_ or _epic_ modes.

### Explorer Mode

- [x] Revisit your `exploring your world` assignment and redo your CSS using flexbox where appropriate.
- [x] Recreate the page 'The Daily Kitteh' using flexbox as closely as you possibly can. Use the same fonts, sizes, and colors. Download some of your favorite
  - ![image](https://suncoast.io/static/daily-kitteh-239ab85408d42833640e2bc1c19aad71-0944d.png)

## Adventure Mode

- [x] Recreate the page `Flebox Article Layout' as closely as possible.
  - ![image](https://suncoast.io/static/flexbox-article-layout-44d4ae2c819d83d964a5cd5916e4943f-03c46.png)

## Epic Mode

- [ ] Recreate the page `Skeleton Layout example` as closely as possible.
  - ![image](https://suncoast.io/static/skeleton-layout-example-041402db4c068aa18658c703443e0443-03c46.png)

## Additional Resources

- https://css-tricks.com/snippets/css/a-guide-to-flexbox/
- http://www.evolutionoftheweb.com

## Recommended Practice:

- https://flexboxfroggy.com/
- https://mastery.games/p/flexbox-zombies

**Comment by benjaminkent** [comment]
explorer mode, adding flex box to my hobbies page complete - https://github.com/benjaminkent/hobbies , http://hobbies-benjaminjehl.surge.sh/

**Comment by benjaminkent** [comment]
Explorer Mode, The Daily Kitteh is complete - http://kitteh-benjaminjehl.surge.sh , https://github.com/benjaminkent/kitteh

**Comment by benjaminkent** [comment]
Adventure Mode Flexbox Article Layout complete - https://github.com/benjaminkent/articles , http://articles-benjaminjehl.surge.sh

**Comment by gstark** [comment]
![Awesome Work!](https://media1.giphy.com/media/1hMe3Ww1bkq2VnNWKz/200w_d.gif)

**Comment by gstark** [comment]
Awesome work!
