### ISSUE TITLE
Week 10  Day 1 - Blog, The Series Finally

### ISSUE THREAD

**Issue by mdewey** [benjaminkent/assignments#33]
We are approaching the final stretch of topics and tonight we will be preparing for the final stretch.

For today, we are going to blogging and practicing everything we have talk about. 

## Objectives
- Practice talking like a developer
- Work on your capstone

## Explorer
- [ ] Blog time. Choose a prompt from the following list
    - Pick 1 topic that we have learned and create a blog post explaining it to a new or non-developer
    - Blog about a struggle that you have encountered and overcame during your tenure here so far. 
    - Pick a new technology that we haven't hit yet (or won't) and create a intro blog for that. 

- [x] Algorithm Practice -- submit a `gist` of your solution for https://www.codewars.com/kata/form-the-minimum in C#, Ruby, and/or  JavaScript

## Adventure
- [ ] Start Suncoast Overflow
- [ ] Work on your capstone project

**Comment by benjaminkent** [comment]
code war done - https://gist.github.com/benjaminkent/479324c80cc04d421643fbbfbd5a013b

**Comment by benjaminkent** [comment]
my blog post! https://medium.com/@benjaminjehl/leaving-finance-for-tech-a056bd603352

**Comment by mdewey** [comment]
Your homework was marked: **Exceeds Expectations**

![Woah](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBCdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5d5eae07a7d338c96b9a2cc704bc5ec7f53d072c/woah.gif)
> &ldquo;Woah&rdquo;
__&mdash; via **[Jason L Perry](https://gifs.suncoast.io/venerations/2)**__
