### ISSUE TITLE
Week 11 Day 1 - Auth0 

### ISSUE THREAD

**Issue by mdewey** [benjaminkent/assignments#35]
---
title: Welcome to Auth0
draft: true
---

We have been chatting about the idea of `authentication` and `authorization`. This is a deep and complex topic, and you, being a good developer, should want to stand on the shoulders of giants to tackle this seemingly simple, yet complex problem. 

## Objectives

* Integrate Auth0 with your favourite frontend framework

## Requirements

- Create an account [here](https://auth0.com).
- follow along with a tutorial to create a simple front-end application. 

### Explorer Mode

* [ ] Using either React, create a new front-end application that uses Auth0 as the user provider. No back-end is needed for this. 
* [ ] Display the name or email, and the user Id to the user after they log in.

#### Tips:

- Here is the sample implication: [https://github.com/mdewey/PlacesIHaveBeen](https://github.com/mdewey/PlacesIHaveBeen)
- For React go [here](https://auth0.com/docs/quickstart/spa/react)
- The implementations in the different frameworks are about 90% the same. 
- Be sure to include the router libraries for the project you create. I would suggest starting here and creating threes pages/components: `home`, `callback`, and `dashboard`

### Adventure Mode

* [ ] Add User Authenication to StackOverflow

### Epic Mode

* [ ] Work on your capstone

**Comment by benjaminkent** [comment]
auth 0 set up, https://github.com/benjaminkent/auth-test

**Comment by mdewey** [comment]
Your homework was marked: **Meets Expectations**

![Ring that bell!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBTQT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fabcecd7c921cc4014bfcce0bd127f9e89ef3986/meets-2.gif)
> &ldquo;Ring that bell!&rdquo;
__&mdash; via **[Mark Dewey](https://gifs.suncoast.io/venerations/62)**__
