### ISSUE TITLE
Final Project - #Ship it - 

### ISSUE THREAD

**Issue by mdewey** [benjaminkent/assignments#37]
With all the work you have been putting into the last 13 weeks, it has all come down to this. Complete your capstone and show it to the world

## Explorer Mode

- [ ] Submit your repository for the capstone project
- [ ] Submit your Url(s) for your capstone project.

**Comment by benjaminkent** [comment]
https://github.com/benjaminkent/findabro, http://www.findabro.net/

**Comment by mdewey** [comment]
Your homework was marked: **Meets Expectations**

![Well done!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBWQT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5adeb8e5322994e0cbd1bcd7685cf653f71d406a/giphy-8.gif)
> &ldquo;Well done!&rdquo;
__&mdash; via **[Gavin Stark](https://gifs.suncoast.io/venerations/73)**__
