### ISSUE TITLE
Demo Day Information - 

### ISSUE THREAD

**Issue by mdewey** [benjaminkent/assignments#38]
With Demo Day approaching we are looking to collect your information.  This is information we will use to share with the community as well as our hiring partners. 

## Explorer Mode

- [ ] Submit a pull request to this file with your updated information [https://github.com/suncoast-devs/demo-day/blob/master/src/profiles.json](https://github.com/suncoast-devs/demo-day/blob/master/src/profiles.json)
- [ ] Submit here the link for the pull request that you create

**Comment by benjaminkent** [comment]
pull request submitted

**Comment by mdewey** [comment]
Your homework was marked: **Meets Expectations**

![Well done!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBUUT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3c87e39487e11776789d2fa19615334abd2e3aab/giphy-1.gif)
> &ldquo;Well done!&rdquo;
__&mdash; via **[Gavin Stark](https://gifs.suncoast.io/venerations/66)**__
