### ISSUE TITLE
Week 02 Day 2 - Scoreboard

### ISSUE THREAD

**Issue by gstark** [benjaminkent/assignments#5]
For this assignment you will creating a simple interactive score board for your favorite sport.

## Requirements

Refer to this mockup to design your page:

![](https://suncoast.io/static/scoreboard-b43872ec1befd35514e90e2a116338b0-fb8a0.png)

- A user should be able to update a score and the teams playing.

### Explorer Mode

- [x] Implement the basic HTML.
- [x] Implement the basic formatting. Do not worry about styling colors, fonts, etc. yet.
- [x] Assign click events to the `update` buttons to update the corresponding values on the page. The score buttons should adjust the current score by a "hard coded" value.

### Adventure Mode

- [ ] Implement a Quarter/Period Tracker that would be appropriate for the sport.
- [ ] Add some styling to make it more presentable. Have fun with it.
- [ ] Make the layout responsive.

### Epic Mode

- [ ] Add a Timer that counts down automatically and updates the period/quarter appropriately.
- [ ] Save/load the information to local storage.
- [ ] Add CSS to the winning teams score to indicate who is currently winning.
- [ ] Add anything else that your sport would have on its score board (e.g. fouls, sacks, shots on goal, etc.).
- [ ] Improve the UX to help making score keeping by your sport easier.

**Comment by benjaminkent** [comment]
explorer mode complete - https://github.com/benjaminkent/scoreboard, http://scoreboard-benjaminjehl.surge.sh

**Comment by gstark** [comment]
Excellent!

**Comment by gstark** [comment]
![Awesome Work!](https://media0.giphy.com/media/1VV4Q7NfooOj0fSFnK/200w_d.gif)
